This is makeindex, version 2.16 [MiKTeX 25.12].
Scanning style file ./kidiplom.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file kidiplom.acn....done (140 entries accepted, 0 rejected).
Sorting entries....done (1017 comparisons).
Generating output file kidiplom.acr....done (93 lines written, 0 warnings).
Output written in kidiplom.acr.
Transcript written in kidiplom.alg.
