This is makeindex, version 2.16 [MiKTeX 25.12].
Scanning style file ./kidiplom.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file kidiplom.acn....done (131 entries accepted, 0 rejected).
Sorting entries....done (977 comparisons).
Generating output file kidiplom.acr....done (76 lines written, 0 warnings).
Output written in kidiplom.acr.
Transcript written in kidiplom.alg.
