# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore FiniteAutomatons.sln
    - name: Build
      run: dotnet build FiniteAutomatons.sln --configuration Release --no-restore
    - name: Test Unit Tests
      run: dotnet test Tests/FiniteAutomatons.UnitTests/FiniteAutomatons.UnitTests.csproj --no-build --verbosity normal
    - name: Test Integration Tests
      run: dotnet test Tests/FiniteAutomatons.IntegrationTests/FiniteAutomatons.IntegrationTests.csproj --no-build --verbosity normal
